version: 1
base:
  base_hourly_currency: 'EUR'
integrations:
  sevDesk:
    API_TOKEN: '<API_TOKEN>'
accounts:
  - public_name: 'Peix GmbH'
    short_name: 'peix'
    projects:
    - short_name: 'iisy'
      name: 'iisy'
      repo: ''
    - short_name: 'mailer'
      name: 'mailer'
      repo: ''
services: 
  developer:
    public_name: 'Senior Fullstack Developer'
    base_hourly_rate: 75
    short_name: 'dev'
  architect:
    short_name: 'arc'
    public_name: 'Cloud & Software Architect'
    base_hourly_rate: 75
  product_engineer:
    public_name: 'Product Engineer'
    short_name: 'pe'